"""add completed_at to orders

Revision ID: 0f6c9be45637
Revises: 62d3a53ac463
Create Date: 2026-05-03 15:56:41.880484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6c9be45637'
down_revision: Union[str, None] = '62d3a53ac463'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'completed_at')
    # ### end Alembic commands ###
