"""initial

Revision ID: 20e2845d58d1
Revises: d74a8ec0d4c3
Create Date: 2026-04-08 20:38:27.961170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '20e2845d58d1'
down_revision: Union[str, None] = 'd74a8ec0d4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=postgresql.ENUM('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype'),
               type_=sa.String(length=20),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'type',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('INCOME', 'EXPENSE', 'TRANSFER', name='transactiontype'),
               existing_nullable=False)
    # ### end Alembic commands ###
