"""add_attachment_uploaded_at

Revision ID: 2b9955636379
Revises: 22776f3373ab
Create Date: 2026-04-12 15:45:45.999565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9955636379'
down_revision: Union[str, None] = '22776f3373ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('attachment_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'attachment_uploaded_at')
    # ### end Alembic commands ###
