"""add test column to journal_attachments

Revision ID: 33e3bc8db8b8
Revises: bf086206f083
Create Date: 2026-06-07 07:49:54.033705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e3bc8db8b8'
down_revision: Union[str, None] = 'bf086206f083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_attachments', sa.Column('test_column', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal_attachments', 'test_column')
    # ### end Alembic commands ###
