"""add_assigned_to_id_to_journal_entries

Revision ID: 42d56e1e914b
Revises: afd1af200ca0
Create Date: 2026-06-26 19:19:13.725970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d56e1e914b'
down_revision: Union[str, None] = 'afd1af200ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('assigned_to_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal_entries', 'users', ['assigned_to_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_entries', type_='foreignkey')
    op.drop_column('journal_entries', 'assigned_to_id')
    # ### end Alembic commands ###
