"""add transaction_id to order_payments

Revision ID: 62d3a53ac463
Revises: 9d1a198cc83a
Create Date: 2026-05-03 11:28:10.268639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d3a53ac463'
down_revision: Union[str, None] = '9d1a198cc83a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_payments', sa.Column('transaction_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'order_payments', ['transaction_id'])
    op.create_foreign_key(None, 'order_payments', 'transactions', ['transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_payments', type_='foreignkey')
    op.drop_constraint(None, 'order_payments', type_='unique')
    op.drop_column('order_payments', 'transaction_id')
    # ### end Alembic commands ###
