"""add_counterparty_remove_product_price

Revision ID: 65cbb062d6be
Revises: c04717d4a6ce
Create Date: 2026-04-21 17:47:53.019005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65cbb062d6be'
down_revision: Union[str, None] = 'c04717d4a6ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'price_per_unit')
    op.add_column('transactions', sa.Column('counterparty', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'counterparty')
    op.add_column('products', sa.Column('price_per_unit', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
