"""add completed_at to orders

Revision ID: 7511bc5028eb
Revises: 0f6c9be45637
Create Date: 2026-05-03 16:39:57.427093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7511bc5028eb'
down_revision: Union[str, None] = '0f6c9be45637'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
