"""add platform to payment_orders

Revision ID: 8b4f67046363
Revises: fbef3e727cad
Create Date: 2026-06-18 10:57:26.327355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b4f67046363'
down_revision: Union[str, None] = 'fbef3e727cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_orders', sa.Column('product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment_orders', 'product_id')
    # ### end Alembic commands ###
