"""add_test_column_to_manufactured_products

Revision ID: 9606b97046c7
Revises: 646b79fb25b6
Create Date: 2026-06-12 21:56:21.727347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9606b97046c7'
down_revision: Union[str, None] = '646b79fb25b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufactured_products', sa.Column('test_column', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manufactured_products', 'test_column')
    # ### end Alembic commands ###
