"""add_icon_to_category_and_fixes

Revision ID: 9d10177357df
Revises: 59446a5d795c
Create Date: 2026-04-10 15:15:11.719725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d10177357df'
down_revision: Union[str, None] = '59446a5d795c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('icon', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'icon')
    # ### end Alembic commands ###
