"""add attachment_url to chat_messages

Revision ID: b2309d8b42bd
Revises: 0fd8132c1af8
Create Date: 2026-04-28 11:43:14.156565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2309d8b42bd'
down_revision: Union[str, None] = '0fd8132c1af8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('attachment_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'attachment_url')
    # ### end Alembic commands ###
