"""add_payment_fields_to_transactions

Revision ID: cd827023fa8c
Revises: 9606b97046c7
Create Date: 2026-06-14 08:05:40.008610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd827023fa8c'
down_revision: Union[str, None] = '9606b97046c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('transactions', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('transactions', sa.Column('payment_due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'payment_due_date')
    op.drop_column('transactions', 'paid_at')
    op.drop_column('transactions', 'is_paid')
    # ### end Alembic commands ###
