"""add transfer_to_account_id to transactions

Revision ID: e98f9e93541c
Revises: 2c272035d71b
Create Date: 2026-04-15 13:56:22.941882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e98f9e93541c'
down_revision: Union[str, None] = '2c272035d71b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
