"""add payment_orders table

Revision ID: fdff411bbee8
Revises: de48a557b2f9
Create Date: 2026-05-14 17:34:21.977705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdff411bbee8'
down_revision: Union[str, None] = 'de48a557b2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_usage')
    op.alter_column('payment_orders', 'amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.drop_constraint('payment_orders_user_id_fkey', 'payment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'payment_orders', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_orders', type_='foreignkey')
    op.create_foreign_key('payment_orders_user_id_fkey', 'payment_orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.alter_column('payment_orders', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    op.create_table('company_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('transactions_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('messages_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tasks_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orders_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_usage_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='company_usage_pkey')
    )
    # ### end Alembic commands ###
