"""add_extra_companies_nullable

Revision ID: ff8e9f69b492
Revises: de48a557b2f9
Create Date: 2026-05-13 12:35:12.719564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff8e9f69b492'
down_revision: Union[str, None] = 'de48a557b2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('company_usage')
    op.drop_table('payment_orders')
    op.alter_column('users', 'extra_companies',
               existing_type=sa.INTEGER(),
               type_=sa.JSON(),
               nullable=True)
    op.drop_column('users', 'subscription_plan')
    op.drop_column('users', 'last_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_login', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('subscription_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.alter_column('users', 'extra_companies',
               existing_type=sa.JSON(),
               type_=sa.INTEGER(),
               nullable=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('plan', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payment_orders_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payment_orders_pkey')
    )
    op.create_table('company_usage',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('transactions_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('messages_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tasks_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orders_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='company_usage_company_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='company_usage_pkey')
    )
    # ### end Alembic commands ###
